theme: jekyll-theme-chirpy
lang: en

timezone: Europe/London
title: Robbie A

tagline: "<div>Welcome to my blog!</div><div style='padding-bottom: 10px;'></div><div>I'm a Software Engineer who likes both trains and data.</div><div style='padding-bottom: 10px;'></div><div>Current projects focus on collecting railway data from the National Rail push port APIs</div><div style='padding-bottom: 10px;'></div><div></div>"

description: >-   
  Blog from Robbie A.

github:
  username: iianderson
social:
  name: Robbie A
  links:
    - https://github.com/iianderson        


# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: '/assets/img/4Y7B9422-4.jpeg'

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active:         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:              # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:           # optional, default to 'pathname'
    input_position:    # optional, default to 'bottom'
    lang:              # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

pwa:
  enabled: false

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
